### ISSUE TITLE
The connection to the server localhost:8080 was refused 

### ISSUE THREAD

**Issue by Chabane** [davidkbainbridge/k8s-playground#8]
Hi @dbainbri-ciena,

Thanks for sharing!

I got this error when I run vagrant up 

```
==> k8s1: TASK [k8s-master : Set --proxy-mode flag in kube-proxy daemonset (workaround for https://github.com/kubernetes/kubernetes/issues/34101)] ***
==> k8s1: fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl -n kube-system get ds -l 'component=kube-proxy' -o json | jq '.items[0].spec.template.spec.containers[0].command |= .+ [\"--proxy-mode=userspace\"]' | kubectl apply -f - && kubectl -n kube-system delete pods -l 'component=kube-proxy'", "delta": "0:00:00.973765", "end": "2017-01-14 10:27:05.438772", "failed": true, "rc": 1, "start": "2017-01-14 10:27:04.465007", "stderr": "The connection to the server localhost:8080 was refused - did you specify the right host or port?\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?", "stdout": "", "stdout_lines": [], "warnings": []}
==> k8s1: 	to retry, use: --limit @/vagrant/ansible/k8s-master.retry
==> k8s1: 
==> k8s1: PLAY RECAP *********************************************************************
==> k8s1: localhost                  : ok=15   changed=11   unreachable=0    failed=1   
```
any idea?

**Comment by dbainbri-ciena** [comment]
@Chabane Thanks for the report. Let me attempt to reproduce it.

**Comment by davidkbainbridge** [comment]
I was able to reproduce this. Apparently something change changed in kubeadm. I will need to work through this.

**Comment by Chabane** [comment]
Thanks davidkbainbridge, 

If you execute this command directly via vagrant it works fine : 

`vagrant ssh k8s1 -c "kubectl -n kube-system get ds -l 'component=kube-proxy' -o json | jq '.items[0].spec.template.spec.containers[0].command |= .+ [\"--proxy-mode=userspace\"]' | kubectl apply -f - && kubectl -n kube-system delete pods -l 'component=kube-proxy'" `
 
but with ansible-playbook, we got an error. 
I tried several stuff but it did not work.

**Comment by davidkbainbridge** [comment]
@Chabane yes, i see the same thing. This would seem to me that there is a timing issue. In other words this second command needs to be executed after some other state exists in the system. If I can identify that, then I can add that to the playbook.
